export {
  loginSchema,
  registerSchema,
  registerDetailsSchema,
  registerOtpSchema,
  forgotPasswordSchema,
  resetPasswordSchema,
  bdPhoneSchema,
  normalizeBdPhoneClient,
  type LoginFormValues,
  type RegisterFormValues,
  type RegisterOtpFormValues,
  type ForgotPasswordFormValues,
  type ResetPasswordFormValues,
} from "./auth.schema";
